### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by fancythedeveloper** [Cos8o/noclip.js#1]
Is there any way to compile this yet? I've tried GCC and such on MSYS2 but it didn't work, even with the extra files it needs.

**Comment by Cos8o** [comment]
you must setup httplib and json.hpp yourself

**Comment by Cos8o** [comment]
What is the issue? Remember that you have to link with winapi, if you're on windows passing "-lkernel32" should be enough; if you're on a different platform you gotta cross compile, that is up to you.

**Comment by fancythedeveloper** [comment]
Kk

**Comment by fancythedeveloper** [comment]
This is what I get with Clang
`$ clang++ server.cpp -o server.exe
server.cpp:64:23: error: use of overloaded operator '+' is ambiguous (with operand types 'unsigned long long' and 'nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::vector<unsigned char, std::allocator<unsigned char>>>::value_type' (aka 'nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::vector<unsigned char, std::allocator<unsigned char>>>'))
                auto address = base + json["address"];
                               ~~~~ ^ ~~~~~~~~~~~~~~~
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, float)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, double)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, long double)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, __float128)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, int)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, long)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, long long)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, __int128)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, unsigned int)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, unsigned long)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, unsigned long long)
server.cpp:64:23: note: built-in candidate operator+(unsigned long long, unsigned __int128)
1 error generated.
`

**Comment by Cos8o** [comment]
Sorry for the late reply, error on my end: for some reason inference doesnt work on clang (works fine on msvc). This will be fixed with a future commit. Also, to use the server you have to compile the file as a DLL:
`clang [-m32 if you're on x64] -shared -o server.dll server.cpp`
